import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import LayoutProvider from './components/Layout/Layout';
import { AuthProvider } from './components/AuthContext/AuthContext';

const JetBrains = JetBrains_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Microservice Full Stack',
    description: 'Generated by create Victor Zarzar',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={JetBrains.className}>
                <AuthProvider>
                    <LayoutProvider>{children}</LayoutProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
