import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { JetBrains_Mono } from 'next/font/google';
import { routing } from '../../i18n/routing';
import LayoutProvider from '../components/Layout/Layout';
import { AuthProvider } from '../contexts/AuthContext';
import type { Locale } from '../types/main';
import NotFound404 from './[...rest]/page';
import './globals.css';

const JetBrains = JetBrains_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Microservice Full Stack',
    description: 'Generated by create Victor Zarzar',
};

export default async function LocaleLayout({ children, params }: { children: React.ReactNode; params: { locale: Locale } }) {
    const { locale } = await Promise.resolve(params);

    if (!routing.locales.includes(locale)) {
        return <NotFound404 />;
    }

    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            <head>
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body className={JetBrains.className}>
                <AuthProvider>
                    <NextIntlClientProvider messages={messages}>
                        <LayoutProvider>{children}</LayoutProvider>
                    </NextIntlClientProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
